//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalCorrectionApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignalCorrectionApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select proper algorithm from list and try again..
        /// </summary>
        internal static string algorithmError {
            get {
                return ResourceManager.GetString("algorithmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter at least one bit to distort and try again. Remeber use integer figures splitted semicolons..
        /// </summary>
        internal static string bitsDistortError {
            get {
                return ResourceManager.GetString("bitsDistortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate bit positions to distort, using integer figures splitted semicolons..
        /// </summary>
        internal static string bitsDistortTooltip {
            get {
                return ResourceManager.GetString("bitsDistortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC 12.
        /// </summary>
        internal static string crc12 {
            get {
                return ResourceManager.GetString("crc12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC 16.
        /// </summary>
        internal static string crc16 {
            get {
                return ResourceManager.GetString("crc16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDLC REVERSE.
        /// </summary>
        internal static string CRC4 {
            get {
                return ResourceManager.GetString("CRC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamming Code.
        /// </summary>
        internal static string hamming {
            get {
                return ResourceManager.GetString("hamming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Detected in Input.
        /// </summary>
        internal static string inputError {
            get {
                return ResourceManager.GetString("inputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Input Text and try again..
        /// </summary>
        internal static string inputTextError {
            get {
                return ResourceManager.GetString("inputTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity Control.
        /// </summary>
        internal static string parity {
            get {
                return ResourceManager.GetString("parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDLC.
        /// </summary>
        internal static string sdlc {
            get {
                return ResourceManager.GetString("sdlc", resourceCulture);
            }
        }
    }
}
